baseurl = "http://ejf.io"
languageCode = "en-us"
title = "E John Feig"
paginate = 10
paginatePath = "page"
disqusShortname = "ejf"

[params]
  author = "E John Feig"
  description = "All of John's random thoughts, musings, and tech stuff in one place. Contact: john at ejf.io"
  gPlusName = "+EJohnFeig"
  twitterName = "emil10001"
  githubName = "emil10001"
  twitter = "true"
