baseurl = "https://ejf.io"
languageCode = "en-us"
title = "E John Feig"
paginate = 10
paginatePath = "page"
disqusShortname = "ejf"

[params]
  author = "E John Feig"
  description = "Random thoughts, musings, and tech stuff"
  gPlusName = "+EJohnFeig"
  twitterName = "emil10001"
  githubName = "emil10001"
  twitter = "true"
  categories = ["android", "coffee", "dev_blog"]
